application: helloworld-1
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: helloworld.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

indexes:
- kind: Greeting
  ancestor: yes
  properties:
  - name: date
    direction: desc